[project]
name = "telegram-mcp-server"
version = "0.1.0"
description = "Telegram MCP server for FastMCP Cloud"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.0.0",
    "httpx",
]

[dependency-groups]
dev = []
